/* Run via agent-browser eval --stdin after loading the local recorded-data harness. */
(async () => {
  if (!window.ready || !window.card) throw new Error('Load the UI fixture harness first');
  const c = window.card, f = window.fixture, checks = [];
  const initial = structuredClone(f), settle = () => new Promise(r => setTimeout(r, 20));
  const ok = (value, name) => { if (!value) throw new Error(name); checks.push(name); };
  const response = content => ({response: {status: 200, content: structuredClone(content)}});
  clearInterval(c._timer); c._timer = null;
  await settle();
  ok(c._op.textContent === 'Печать завершена', 'completed status does not become ironing');
  ok(c._input.value === '250', 'initial layer is reported layer 250');
  c._input.value = '186'; await c._inspect();
  ok(c._plan.layer === 186 && c._planBox.textContent.includes('Глажка'), 'actual layer 186 explains ironing');
  ok(c._planBox.textContent.includes('не утверждение о текущем движении'), 'planned versus current distinction is visible');
  await c._poll(); ok(c._plan.layer === 186, 'manual layer survives status refresh');
  c._currentButton.click(); ok(c._plan.layer === 250 && c._input.value === '250', 'current layer returns immediately');
  let count = window.calls.length; c._input.value = '-1'; await c._inspect();
  ok(window.calls.length === count && c._error.textContent, 'negative layer rejected before network');
  c._input.value = '1.5'; await c._inspect();
  ok(window.calls.length === count, 'fractional layer rejected before network');
  c._input.value = '99'; await c._inspect();
  ok(c._error.textContent.includes('Такого слоя нет'), 'missing layer has specific error');
  f.status.operation = {label:'Глажка',source:'gcode_cursor',estimated:true,note:'Позиция может опережать движение'};
  await c._poll(); ok(c._op.textContent.startsWith('≈ ') && c._source.textContent.includes('оценка'), 'cursor estimate is marked');
  f.status.stale = true; await c._poll();
  ok(c._fresh.textContent.includes('последние известные') && !c._progress.hasAttribute('value'), 'stale data warning and no current progress');
  window.mode = 'offline'; await c._poll();
  ok(c._op.textContent === 'Текущая операция не подтверждена' && c._fresh.textContent.includes('Нет связи'), 'API failure does not preserve a live operation claim');
  window.mode = 'normal'; f.status = structuredClone(initial.status); await c._poll();
  ok(c._op.textContent === 'Печать завершена' && !c._error.textContent, 'recovery clears error');
  f.layer.features[0].label = '<img src=x onerror="window.injected=true">';
  c._input.value = '186'; await c._inspect();
  ok(!c._planBox.querySelector('img') && c._planBox.textContent.includes('<img') && !window.injected, 'feature text cannot inject HTML');
  f.layer = structuredClone(initial.layer); c._currentButton.click(); window.mode = 'delayed';
  c._input.value = '186'; const old = c._inspect(); await settle();
  c._currentButton.click(); window.pending.shift().resolve(response(f.layer)); await old;
  ok(c._plan.layer === 250 && c._follow, 'late inspection cannot override return-to-current');
  c._input.value = '186'; const a = c._inspect(); await settle();
  c._input.value = '250'; const b = c._inspect(); await settle();
  const one = window.pending.shift(), two = window.pending.shift();
  two.resolve(response(f.status.layer_plan)); await b; one.resolve(response(f.layer)); await a;
  ok(c._plan.layer === 250, 'latest inspection wins out-of-order responses');
  c._input.value = '186'; const stale = c._inspect(); await settle();
  f.status.job_fingerprint = 'f'.repeat(64); await c._poll();
  window.pending.shift().resolve(response(f.layer)); await stale;
  ok(c._plan.layer === 250 && c._follow, 'job change rejects old layer result');
  f.status = structuredClone(initial.status); window.mode = 'normal'; await c._poll();
  window.mode = 'delayed'; c._input.value = '186'; const detached = c._inspect(); await settle();
  const parent = c.parentElement; c.remove(); window.pending.shift().resolve(response(f.layer)); await detached;
  ok(c._plan.layer === 250, 'detached card ignores pending response');
  window.mode = 'normal'; parent.append(c); await settle(); clearInterval(c._timer); c._timer = null;
  ok(c._inspectButton.getBoundingClientRect().height >= 44 && c._currentButton.getBoundingClientRect().height >= 44, 'buttons meet 44px height');
  ok(document.documentElement.scrollWidth <= window.innerWidth, 'no horizontal viewport overflow');
  ok(c.getGridOptions().columns === 12, 'HA section grid options provided');
  return {passed:checks.length,checks};
})()
