import io
import pytest
from u1_gcode_index import GCodeIndex
from u1_print_inspector import enrich, safe_filename, Inspector

SAMPLE = b'''; generated by Snapmaker Orca 2.3.5
SET_PRINT_STATS_INFO TOTAL_LAYER=2 CURRENT_LAYER=0
M83
M109 S200
;LAYER_CHANGE
;Z:0.2
SET_PRINT_STATS_INFO CURRENT_LAYER=1
;TYPE:Outer wall
G1 X1 E1
;TYPE:Top surface
G1 X2 E2
;TYPE:Ironing
G1 X3 E0.1
;LAYER_CHANGE
;Z:0.4
SET_PRINT_STATS_INFO CURRENT_LAYER=2
;TYPE:Support interface
T2
G1 X4 E1
M73 P90 R2
PRINT_END
'''


def idx(data=SAMPLE):
    return GCodeIndex.parse(io.BytesIO(data))


def state(index=None, **kw):
    i = index or idx()
    d = {'print_stats': {'state':'printing','filename':'part.gcode','info':{'current_layer':1,'total_layer':2}},
         'virtual_sdcard': {'file_size':i.size,'file_position':SAMPLE.index(b'G1 X3')},
         'extruder2':{'extruder_index':2,'temperature':199,'target':200},
         'toolhead':{'extruder':'extruder2'}, 'print_task_config':{'filament_type':['PLA','PLA','PETG']}}
    d.update(kw)
    return d


def test_layer_features_and_ironing():
    i = idx(); assert len(i.layers)==2
    assert i.layer(1)['z_mm']==.2
    assert [f['key'] for f in i.layer(1)['features']]==['outer wall','top surface','ironing']
    assert i.summary()['ironing_layers']==[1]
    assert i.layer(1)['positive_extrusion_mm']==3.1
    assert i.layer(2)['logical_tools']==[2]


def test_gcode_cursor_is_explicit_estimate():
    d = enrich(state(),idx())
    assert d['operation']['label']=='Глажка'
    assert d['operation']['estimated'] is True
    assert d['operation']['source']=='gcode_cursor'
    assert d['physical_tool']==2 and d['material']=='PETG'


@pytest.mark.parametrize('s,label',[('complete','Печать завершена'),('paused','Пауза'),('cancelled','Печать отменена'),('error','Ошибка печати'),('standby','Ожидание')])
def test_persistent_cursor_not_current_after_print(s,label):
    st=state();st['print_stats']['state']=s
    d=enrich(st,idx());assert d['operation']['label']==label
    assert not d['operation']['estimated']


def test_stale_has_priority():
    assert enrich(state(),idx(),stale=True)['operation']['label']=='Нет свежих данных'


@pytest.mark.parametrize('action,label',[(200,'Автоочистка сопла'),(3,'Прогрев камеры'),(128,'Восстановление после отключения питания'),(132,'Проверка смены головки'),(201,'Ожидание остывания сопла')])
def test_firmware_action_priority(action,label):
    d=enrich(state(machine_state_manager={'main_state':1,'action_code':action}),idx())
    assert d['operation']['label']==label and not d['operation']['estimated']


def test_calibration_overrides_last_completed_job():
    st=state();st['print_stats']['state']='complete';st['machine_state_manager']={'main_state':3}
    assert enrich(st,idx())['operation']['label']=='Калибровка стола'


def test_unknown_code_not_guessed():
    assert '#999' in enrich(state(machine_state_manager={'action_code':999}),idx())['operation']['label']


def test_no_cursor_only_layer_plan():
    st=state();st['virtual_sdcard'].pop('file_position')
    d=enrich(st,idx());assert d['operation']['source']=='layer_only'
    assert d['operation']['label']!='Глажка'
    assert any(f['key']=='ironing' for f in d['layer_plan']['features'])


def test_changed_size_no_inference():
    st=state();st['virtual_sdcard']['file_size']+=1
    assert enrich(st,idx())['operation']['source']=='layer_only'


def test_utf8_crlf_byte_offsets():
    data='; русский комментарий\r\n;LAYER:0\r\n;TYPE:Ironing\r\nG1 X1\r\n'.encode()
    i=idx(data); assert i.size==len(data)
    assert i.at(data.index(b'G1')).feature=='ironing'
    assert i.at(len(data)) is None


@pytest.mark.parametrize('data',[b'GCDE123\0',b'PK\x03\x04foo',b'abc\0def'])
def test_binary_rejected(data):
    with pytest.raises(ValueError):idx(data)


def test_bounded_size_and_line():
    with pytest.raises(ValueError):GCodeIndex.parse(io.BytesIO(SAMPLE),max_bytes=10)
    with pytest.raises(ValueError):idx(b';'+b'a'*(256*1024))


def test_unannotated_not_inferred_from_speed():
    i=idx(b'G1 X1 E0.001 F20\n');assert i.warnings
    assert not i.all_features


@pytest.mark.parametrize('name',['../x.gcode','a/../x.gcode','/x.gcode','a//x.gcode','a\\x.gcode','x.gcode\n','https://evil/x.gcode','x.bgcode','x.zip','x.3mf'])
def test_filename_safety(name):
    with pytest.raises(ValueError):safe_filename(name)


def test_encoded_filename_and_no_url_injection():
    assert safe_filename('folder/my #?%.gcode')=='folder/my%20%23%3F%25.gcode'


def test_layer_out_of_range():
    with pytest.raises(ValueError):idx(b'SET_PRINT_STATS_INFO CURRENT_LAYER=999999\n')
    with pytest.raises(ValueError):idx(b';LAYER:999999\n')


def test_gcode_tool_interval_does_not_leak():
    i=idx();assert i.at(SAMPLE.index(b'T2\n')).operation=='Смена инструмента: T2'
    assert i.at(SAMPLE.index(b'G1 X4')).operation is None


def test_absolute_relative_extrusion_and_resets():
    i=idx(b';LAYER:0\nM82\nG1 E5\nG1 E4\nG92 E0\nG1 E2\nM83\nG1 E1\n')
    assert i.layer(1)['positive_extrusion_mm']==8


def test_meta_layer_without_duplication():
    i=idx(b';LAYER_CHANGE\n; layer num/total_layer_count: 1/2\n;Z:0.2\n;FEATURE:Ironing\nG1 E1\n;LAYER_CHANGE\n; layer num/total_layer_count: 2/2\n;Z:0.4\nG1 E1\n')
    assert sorted(i.layers)==[1,2] and i.declared_layers==2
    assert i.layer(2)['features']==[]


@pytest.mark.parametrize('feature,key',[('WALL-OUTER','outer wall'),('External perimeter','outer wall'),('Support material interface','support interface'),('FILL','sparse infill'),('SKIN','top/bottom skin')])
def test_slicer_aliases(feature,key):
    i=idx(f';LAYER:0\n;TYPE:{feature}\nG1 X1\n'.encode());assert key in i.all_features


def test_m73_remaining_is_slicer_estimate():
    st=state();st['virtual_sdcard']['file_position']=SAMPLE.index(b'PRINT_END');st['print_stats']['info']['current_layer']=2
    d=enrich(st,idx());assert d['remaining_seconds']==120 and d['remaining_source']=='slicer_M73_estimate'


def test_layer_api_job_guard():
    ins=Inspector('http://127.0.0.1:7125');ins.index=idx()
    assert ins.layer(1,'wrong')[0]==409
    assert ins.layer(99)[0]==404
    assert ins.layer(1,ins.index.sha256)[0]==200
    ins.executor.shutdown()


@pytest.mark.parametrize('url',['file:///tmp/a','http://a/path','http://user:pass@a','http://a?x=1'])
def test_origin_safety(url):
    with pytest.raises(ValueError):Inspector(url)
